export type CalendarSizeId = "xs" | "sm" | "md" | "lg" | "xl";

export interface CalendarSize {
  id: CalendarSizeId;
  label: string;
  cell: number;
  gap: number;
  chips: number;
}

export const CALENDAR_SIZES: CalendarSize[] = [
  { id: "xs", label: "Mini", cell: 52, gap: 4, chips: 1 },
  { id: "sm", label: "Compatto", cell: 68, gap: 6, chips: 1 },
  { id: "md", label: "Normale", cell: 88, gap: 8, chips: 2 },
  { id: "lg", label: "Grande", cell: 112, gap: 10, chips: 3 },
  { id: "xl", label: "Maxi", cell: 136, gap: 12, chips: 3 },
];

export interface CalendarModel {
  id: string;
  name: string;
  description: string;
  preview: string;
  radius: number;
  frame: string;
  header: string;
  weekday: string;
  cell: string;
  cellOn: string;
  today: string;
  chip: string;
  empty: string;
  showWeekNumbers?: boolean;
}

export const CALENDAR_MODELS: CalendarModel[] = [
  {
    id: "griglia-classica",
    name: "Griglia classica",
    description: "Mese pulito, celle arrotondate",
    preview: "linear-gradient(160deg,#1a1a2e,#0d4f2b)",
    radius: 16,
    frame: "border border-white/10 bg-[var(--team-card-bg)]",
    header: "font-black",
    weekday: "uppercase opacity-70",
    cell: "border border-white/10 bg-white/5",
    cellOn: "border-[var(--team-accent)] bg-[var(--team-accent)]/15",
    today: "text-[var(--team-accent)]",
    chip: "bg-black/35",
    empty: "bg-white/5",
  },
  {
    id: "campo-verde",
    name: "Campo verde",
    description: "Righe da prato da stadio",
    preview: "repeating-linear-gradient(90deg,#147a38 0 18px,#0f5c2a 18px 36px)",
    radius: 8,
    frame: "border-2 border-white/40 bg-[#0b3d1c]",
    header: "font-black tracking-wide text-white",
    weekday: "uppercase text-white/80",
    cell: "border border-white/20 bg-[#147a38]/70",
    cellOn: "border-yellow-300 bg-yellow-300/25",
    today: "text-yellow-200",
    chip: "bg-black/40",
    empty: "bg-[#0f5c2a]/80",
  },
  {
    id: "neon-notte",
    name: "Neon notte",
    description: "Bordi luminescenti su nero",
    preview: "linear-gradient(160deg,#050510,#1b0540)",
    radius: 18,
    frame: "border border-fuchsia-400/40 bg-black/70 shadow-[0_0_24px_rgba(232,121,249,0.25)]",
    header: "font-black text-fuchsia-200",
    weekday: "uppercase text-cyan-300/80",
    cell: "border border-cyan-400/30 bg-black/40",
    cellOn: "border-fuchsia-400 bg-fuchsia-500/20 shadow-[0_0_12px_rgba(232,121,249,0.45)]",
    today: "text-cyan-300",
    chip: "bg-fuchsia-500/30",
    empty: "bg-black/30",
  },
  {
    id: "agenda-carta",
    name: "Agenda carta",
    description: "Foglio da planner, linee sottili",
    preview: "linear-gradient(180deg,#f4efe4,#e4d7c0)",
    radius: 4,
    frame: "border border-amber-900/30 bg-[#f3ead8] text-zinc-900",
    header: "font-black text-zinc-900",
    weekday: "uppercase text-zinc-700",
    cell: "border border-amber-900/20 bg-white/70 text-zinc-900",
    cellOn: "border-amber-700 bg-amber-200",
    today: "text-amber-800",
    chip: "bg-amber-900/15 text-zinc-900",
    empty: "bg-amber-100/50",
  },
  {
    id: "mosaico",
    name: "Mosaico",
    description: "Tessere colorate da tribuna",
    preview: "linear-gradient(135deg,#e11d48,#f59e0b,#22c55e,#3b82f6)",
    radius: 20,
    frame: "border-0 bg-gradient-to-br from-rose-600/30 via-amber-500/20 to-sky-500/30",
    header: "font-black",
    weekday: "uppercase opacity-80",
    cell: "border-0 bg-white/10",
    cellOn: "bg-[var(--team-accent)] text-[var(--team-secondary)]",
    today: "underline decoration-2",
    chip: "bg-black/30",
    empty: "bg-black/20",
  },
  {
    id: "vetro-frost",
    name: "Vetro frost",
    description: "Celle traslucide da vetrina",
    preview: "linear-gradient(160deg,#94a3b8,#e2e8f0)",
    radius: 22,
    frame: "border border-white/25 bg-white/10 backdrop-blur-xl",
    header: "font-semibold tracking-tight",
    weekday: "uppercase text-white/70",
    cell: "border border-white/20 bg-white/10 backdrop-blur",
    cellOn: "border-white bg-white/25",
    today: "text-white",
    chip: "bg-white/15",
    empty: "bg-white/5",
  },
  {
    id: "carbonio",
    name: "Carbonio",
    description: "Scuro tecnico da panchina",
    preview: "repeating-linear-gradient(45deg,#111 0 8px,#1a1a1a 8px 16px)",
    radius: 10,
    frame: "border border-zinc-600 bg-zinc-950",
    header: "font-black tracking-widest uppercase text-zinc-200",
    weekday: "uppercase text-zinc-400",
    cell: "border border-zinc-700 bg-zinc-900",
    cellOn: "border-zinc-300 bg-zinc-700",
    today: "text-zinc-100",
    chip: "bg-zinc-800",
    empty: "bg-black",
  },
  {
    id: "cornice-oro",
    name: "Cornice oro",
    description: "Lusso da coppa",
    preview: "linear-gradient(160deg,#3b2a08,#d4af37)",
    radius: 6,
    frame: "border-4 border-amber-400 bg-[#1a1408] shadow-[inset_0_0_0_2px_#7a5b12]",
    header: "font-black text-amber-300",
    weekday: "uppercase text-amber-200/80",
    cell: "border border-amber-400/30 bg-black/40",
    cellOn: "border-amber-300 bg-amber-400/20",
    today: "text-amber-200",
    chip: "bg-amber-500/20",
    empty: "bg-black/30",
  },
  {
    id: "lavagna",
    name: "Lavagna mister",
    description: "Gesso su verde scuola",
    preview: "linear-gradient(160deg,#12351f,#1f5a36)",
    radius: 2,
    frame: "border-8 border-[#5b3a1e] bg-[#163322]",
    header: "font-black italic text-lime-100",
    weekday: "uppercase text-lime-200/70",
    cell: "border border-white/10 bg-transparent",
    cellOn: "border-lime-300 bg-lime-300/15",
    today: "text-lime-200",
    chip: "bg-lime-950/50",
    empty: "bg-black/20",
  },
  {
    id: "biglietto",
    name: "Biglietto gara",
    description: "Stile ticket da stadio",
    preview: "linear-gradient(90deg,#111,#e11d48 50%,#111)",
    radius: 14,
    frame: "border-2 border-dashed border-white/50 bg-[#111827]",
    header: "font-black uppercase",
    weekday: "uppercase tracking-[0.2em] text-xs",
    cell: "border border-white/15 bg-[#0b1220]",
    cellOn: "border-rose-400 bg-rose-500/20",
    today: "text-rose-300",
    chip: "bg-rose-600/40",
    empty: "bg-black/40",
  },
  {
    id: "polare",
    name: "Polare",
    description: "Ghiaccio e blu artico",
    preview: "linear-gradient(160deg,#0ea5e9,#e0f2fe)",
    radius: 24,
    frame: "border border-sky-200/40 bg-sky-950/80",
    header: "font-black text-sky-100",
    weekday: "uppercase text-sky-200/80",
    cell: "border border-sky-300/20 bg-sky-900/40",
    cellOn: "border-sky-200 bg-sky-400/25",
    today: "text-sky-200",
    chip: "bg-sky-500/30",
    empty: "bg-sky-950/50",
  },
  {
    id: "tramonto",
    name: "Tramonto",
    description: "Arancio e viola da fine gara",
    preview: "linear-gradient(160deg,#7c2d12,#f97316,#7e22ce)",
    radius: 18,
    frame: "border-0 bg-gradient-to-br from-orange-700/40 via-rose-700/30 to-violet-800/40",
    header: "font-black text-orange-100",
    weekday: "uppercase text-orange-200/80",
    cell: "border border-orange-300/20 bg-black/25",
    cellOn: "border-orange-300 bg-orange-400/25",
    today: "text-orange-200",
    chip: "bg-violet-600/40",
    empty: "bg-black/20",
  },
  {
    id: "ledger",
    name: "Ledger",
    description: "Tabella da segreteria",
    preview: "linear-gradient(180deg,#e5e7eb,#9ca3af)",
    radius: 0,
    frame: "border border-white/20 bg-black/50",
    header: "font-semibold uppercase tracking-widest text-sm",
    weekday: "uppercase text-[10px] opacity-60",
    cell: "border border-white/15 bg-transparent",
    cellOn: "bg-white/15",
    today: "font-black",
    chip: "border border-white/20 bg-transparent",
    empty: "bg-white/5",
    showWeekNumbers: true,
  },
  {
    id: "poster-mese",
    name: "Poster mese",
    description: "Mese enorme, celle ampie",
    preview: "linear-gradient(160deg,#111827,#4f46e5)",
    radius: 28,
    frame: "border border-indigo-400/30 bg-indigo-950/50",
    header: "text-3xl font-black",
    weekday: "uppercase tracking-widest opacity-60",
    cell: "border-0 bg-indigo-500/10",
    cellOn: "bg-indigo-400/30",
    today: "text-indigo-200",
    chip: "bg-indigo-950/60",
    empty: "bg-indigo-950/30",
  },
  {
    id: "denso",
    name: "Denso",
    description: "Tante info in poco spazio",
    preview: "linear-gradient(160deg,#0f172a,#334155)",
    radius: 8,
    frame: "border border-white/10 bg-slate-950",
    header: "text-base font-bold",
    weekday: "text-[10px] uppercase opacity-50",
    cell: "border border-white/10 bg-slate-900",
    cellOn: "border-white/40 bg-slate-700",
    today: "text-white",
    chip: "bg-slate-800",
    empty: "bg-slate-950",
  },
  {
    id: "magazine",
    name: "Magazine",
    description: "Copertina da matchday",
    preview: "linear-gradient(160deg,#be123c,#111)",
    radius: 20,
    frame: "border border-rose-500/30 bg-gradient-to-b from-rose-950/80 to-black",
    header: "font-black italic",
    weekday: "uppercase text-rose-200/70",
    cell: "border border-white/10 bg-black/30",
    cellOn: "border-rose-400 bg-rose-500/20",
    today: "text-rose-200",
    chip: "bg-rose-900/50",
    empty: "bg-black/40",
  },
  {
    id: "minimal-linee",
    name: "Minimal linee",
    description: "Solo tratti, tanto respiro",
    preview: "linear-gradient(160deg,#0a0a0a,#404040)",
    radius: 0,
    frame: "border-0 bg-transparent",
    header: "font-light tracking-tight",
    weekday: "uppercase text-[11px] opacity-40",
    cell: "border-b border-white/15 bg-transparent",
    cellOn: "border-b-2 border-[var(--team-accent)] bg-white/5",
    today: "text-[var(--team-accent)]",
    chip: "bg-transparent border border-white/10",
    empty: "bg-transparent",
  },
  {
    id: "retro-90",
    name: "Retro 90",
    description: "Telecronaca anni Novanta",
    preview: "linear-gradient(90deg,#22c55e,#facc15,#ef4444)",
    radius: 0,
    frame: "border-4 border-yellow-300 bg-green-800",
    header: "font-black uppercase text-yellow-200",
    weekday: "uppercase text-yellow-100",
    cell: "border-2 border-yellow-300/50 bg-green-700/80",
    cellOn: "border-yellow-200 bg-yellow-400 text-black",
    today: "text-yellow-200",
    chip: "bg-black text-yellow-200",
    empty: "bg-green-900",
  },
  {
    id: "luci-stadio",
    name: "Luci stadio",
    description: "Riflettori sul rettangolo",
    preview: "radial-gradient(circle at top,#fff7,#020617 55%)",
    radius: 16,
    frame: "border border-white/20 bg-[#020617] shadow-[inset_0_40px_80px_rgba(255,255,255,0.08)]",
    header: "font-black",
    weekday: "uppercase opacity-70",
    cell: "border border-white/10 bg-white/5",
    cellOn: "border-white bg-white/15",
    today: "text-white",
    chip: "bg-black/50",
    empty: "bg-black/40",
  },
  {
    id: "hex-tech",
    name: "Hex tech",
    description: "Griglia tecnica da analista",
    preview: "linear-gradient(135deg,#0f766e,#134e4a)",
    radius: 12,
    frame: "border border-teal-400/40 bg-teal-950/70",
    header: "font-black tracking-wider text-teal-100",
    weekday: "uppercase text-teal-200/70",
    cell: "border border-teal-400/20 bg-teal-900/40",
    cellOn: "border-teal-200 bg-teal-400/25",
    today: "text-teal-200",
    chip: "bg-teal-800/70",
    empty: "bg-teal-950/50",
  },
];

export function getCalendarModel(id?: string) {
  return CALENDAR_MODELS.find((m) => m.id === id) || CALENDAR_MODELS[0];
}

export function getCalendarSize(id?: string) {
  return CALENDAR_SIZES.find((s) => s.id === id) || CALENDAR_SIZES[2];
}
