export const APP_PROBES: { name: string; url: string; scheme: string }[] = [
  { name: "WhatsApp", url: "whatsapp://", scheme: "whatsapp" },
  { name: "Instagram", url: "instagram://", scheme: "instagram" },
  { name: "Facebook", url: "fb://", scheme: "fb" },
  { name: "Messenger", url: "fb-messenger://", scheme: "fb-messenger" },
  { name: "Telegram", url: "tg://", scheme: "tg" },
  { name: "TikTok", url: "tiktok://", scheme: "tiktok" },
  { name: "YouTube", url: "youtube://", scheme: "youtube" },
  { name: "X / Twitter", url: "twitter://", scheme: "twitter" },
  { name: "Threads", url: "barcelona://", scheme: "barcelona" },
  { name: "Snapchat", url: "snapchat://", scheme: "snapchat" },
  { name: "LinkedIn", url: "linkedin://", scheme: "linkedin" },
  { name: "Spotify", url: "spotify://", scheme: "spotify" },
  { name: "Netflix", url: "nflx://", scheme: "nflx" },
  { name: "Amazon", url: "com.amazon.mobile.shopping://", scheme: "com.amazon.mobile.shopping" },
  { name: "Gmail", url: "googlegmail://", scheme: "googlegmail" },
  { name: "Google Maps", url: "comgooglemaps://", scheme: "comgooglemaps" },
  { name: "Chrome", url: "googlechrome://", scheme: "googlechrome" },
  { name: "Google Drive", url: "googledrive://", scheme: "googledrive" },
  { name: "Google Photos", url: "googlephoto://", scheme: "googlephoto" },
  { name: "FaceTime", url: "facetime://", scheme: "facetime" },
  { name: "Signal", url: "sgnl://", scheme: "sgnl" },
  { name: "Viber", url: "viber://", scheme: "viber" },
  { name: "Discord", url: "discord://", scheme: "discord" },
  { name: "Telegram K", url: "telegram://", scheme: "telegram" },
  { name: "Slack", url: "slack://", scheme: "slack" },
  { name: "Teams", url: "msteams://", scheme: "msteams" },
  { name: "Zoom", url: "zoomus://", scheme: "zoomus" },
  { name: "Twitch", url: "twitch://", scheme: "twitch" },
  { name: "Pinterest", url: "pinterest://", scheme: "pinterest" },
  { name: "Reddit", url: "reddit://", scheme: "reddit" },
  { name: "PayPal", url: "paypal://", scheme: "paypal" },
  { name: "Revolut", url: "revolut://", scheme: "revolut" },
  { name: "Satispay", url: "satispay://", scheme: "satispay" },
  { name: "Uber", url: "uber://", scheme: "uber" },
  { name: "Deliveroo", url: "deliveroo://", scheme: "deliveroo" },
  { name: "Glovo", url: "glovo://", scheme: "glovo" },
  { name: "Just Eat", url: "justeat://", scheme: "justeat" },
  { name: "CapCut", url: "capcut://", scheme: "capcut" },
  { name: "Shazam", url: "shazam://", scheme: "shazam" },
  { name: "SoundCloud", url: "soundcloud://", scheme: "soundcloud" },
  { name: "Booking", url: "bookings://", scheme: "bookings" },
  { name: "Airbnb", url: "airbnb://", scheme: "airbnb" },
  { name: "Apple Maps", url: "maps://", scheme: "maps" },
  { name: "App Store", url: "itms-apps://", scheme: "itms-apps" },
  { name: "Phone", url: "tel://", scheme: "tel" },
  { name: "Messaggi", url: "sms://", scheme: "sms" },
  { name: "Mail", url: "mailto://", scheme: "mailto" },
  { name: "Calendario", url: "calshow://", scheme: "calshow" },
];

export const APP_SCHEMES = [...new Set(APP_PROBES.map((a) => a.scheme))];
